updateos exit code fix.

diff --git a/updateos b/updateos
--- a/updateos
+++ b/updateos
@@ -45,13 +45,14 @@ for script in `/usr/bin/curl -ls $BACKEND/$GROUP/$SUBGROUP/ | sed 's/<a\ href=/~
   echo "----> Running $GROUP $SUBGROUP $script..." | tee -a /tmp/updateos.log
   /usr/bin/curl -s $BACKEND/$GROUP/$SUBGROUP/$script -o /tmp/.${script}
   chmod +x /tmp/.${script}
-  /tmp/.${script} $3 $4 $5 $6 $7 2>&1 | tee -a /tmp/updateos.log
-  [ "$?" != "0" ] && echo "Failed." && echo "" && exit $?
+  /tmp/.${script} $3 $4 $5 $6 $7 2>&1
+  EXIT=$?
+  [ "$EXIT" != "0" ] && echo "Failed." | tee -a /tmp/updateos.log && echo "" && exit $EXIT
   echo "Success." | tee -a /tmp/updateos.log
   echo "" | tee -a /tmp/updateos.log
   rm -f /tmp/.${script}
   done
-exit $?
+exit $EXIT
 }
 
 run_script() {
@@ -59,11 +60,13 @@ echo "----> Running $SCRIPT ..." | tee -a /tmp/updateos.log
 /usr/bin/curl -s $BACKEND/${GROUP}/${SCRIPT} -o /tmp/.${SCRIPT}
 [ "`cat /tmp/.${SCRIPT} | grep HTML`" != "" ] && echo "Script does not exist." | tee -a /tmp/updateos.log && echo "" | tee -a /tmp/updateos.log && rm -f /tmp/.${SCRIPT} && usage
 chmod +x /tmp/.${SCRIPT}
-/tmp/.${SCRIPT} $3 $4 $5 $6 $7 2>&1 | tee -a /tmp/updateos.log
-[ "$?" != "0" ] && echo "Failed." && echo "" && exit $?
+/tmp/.${SCRIPT} $3 $4 $5 $6 $7 2>&1
+EXIT=$?
+[ "$EXIT" != "0" ] && echo "Failed." | tee -a /tmp/updateos.log && echo "" && exit $EXIT
 echo "Success." | tee -a /tmp/updateos.log
 echo "" | tee -a /tmp/updateos.log
-exit $?
+rm -f /tmp/.${SCRIPT}
+exit $EXIT
 }
 
 # main
