new core script.

diff --git a/updateos_new b/updateos_new
--- a/updateos_new
+++ b/updateos_new
@@ -5,7 +5,7 @@ ID=$(/usr/bin/id -u)
 [ $ID -ne 0 ] && echo "You must be root to run $0." && exit 1
 
 #Init
-VERSION="1.18.1"
+VERSION="1.18.3"
 LOG_FILE="/tmp/updateos.log"
 BACKEND="http://rhel8repo.centralus.cloudapp.azure.com/ostools-1.17"
 [ "`echo $#`" -ge "2" ] && export CMDLINEVARS="`echo $@ | cut -d" " -f2-`" || export CMDLINEVARS=""
@@ -51,33 +51,18 @@ exit 0
 }
 
 run_subgroup() {
-for SCRIPT in `/usr/bin/curl -ls $BACKEND/$GROUP/$SUBGROUP/ | grep -v $SUBGROUP | sed 's/<a\ href=/~/g'  | grep -v colspan | cut -d~ -f2 | cut -d\" -f2 | grep -v \< | grep -v \/\/ | grep -v \? | grep -v ^/ | grep -v \/ | grep -v .md5 | grep -v nopub`
+  [ "$NETUP" != "Y" ] && log "Internet down. No subgroups without internet." && return 0
+    for SCRIPT in `/usr/bin/curl -ls $BACKEND/$GROUP/$file | grep -v $file | sed 's/<a\ href=/~/g'  | grep -v colspan | cut -d~ -f2 | cut -d\" -f2 | grep -v \< | grep -v \/\/ | grep -v \? | grep -v ^/ | grep -v \/ | grep -v .md5 | grep -v nopub`
   do
-  echo "----> `date` - Running $GROUP $SUBGROUP $SCRIPT..." | tee -a /tmp/updateos.log
-  [ ! -f /usr/bin/.updateos/$SCRIPT ] && touch /usr/bin/.updateos/$SCRIPT
-    [ "`curl -s $BACKEND/$GROUP/$SCRIPT.md5`" != "`md5sum /usr/bin/.updateos/$SCRIPT | cut -d" " -f1`" ] && download_script
-  /usr/bin/.updateos/${SCRIPT} 2>&1 | tee -a /tmp/updateos.log
-  EXIT="${PIPESTATUS[0]}"
-  [ "$EXIT" != "0" ] && echo "Failed." | tee -a /tmp/updateos.log && echo "" && exit $EXIT
-  echo "----> `date` - Success." | tee -a /tmp/updateos.log
-  echo "" | tee -a /tmp/updateos.log
-  done
+      log "----> `date` - Running $GROUP $SUBGROUP $SCRIPT..."
+      download_script
+      /usr/bin/.updateos/${SCRIPT} 2>&1 | tee -a $LOG_FILE
+      EXIT="${PIPESTATUS[0]}"
+      [ "$EXIT" != "0" ] && log "Failed." && exit $EXIT
+      log "----> `date` - Success."
+    done
 exit $EXIT
 }
-
-#run_subgroup() {
-#  [ "$NETUP" != "Y" ] && log "Internet down. No subgroups without internet." && return 0
-#    for SCRIPT in `/usr/bin/curl -ls $BACKEND/$GROUP/$file | grep -v $file | sed 's/<a\ href=/~/g'  | grep -v colspan | cut -d~ -f2 | cut -d\" -f2 | grep -v \< | grep -v \/\/ | grep -v \? | grep -v ^/ | grep -v \/ | grep -v .md5 | grep -v nopub`
-#  do
-#      log "----> `date` - Running $GROUP $SUBGROUP $SCRIPT..."
-#      download_script
-#      /usr/bin/.updateos/${SCRIPT} 2>&1 | tee -a $LOG_FILE
-#      EXIT="${PIPESTATUS[0]}"
-#      [ "$EXIT" != "0" ] && log "Failed." && exit $EXIT
-#      log "----> `date` - Success."
-#    done
-#exit $EXIT
-#}
 
 run_script() {
   SUBGROUP=""
@@ -100,17 +85,10 @@ download_script () {
   [ "`curl -s $BACKEND/$GROUP/$SCRIPT.md5`" != "`md5sum /usr/bin/.updateos/$SCRIPT | cut -d" " -f1`" ] && rm -f /usr/bin/.updateos/$SCRIPT && /usr/bin/curl -s $BACKEND/$GROUP/$SUBGROUP/$SCRIPT -o /usr/bin/.updateos/$SCRIPT && chmod +x /usr/bin/.updateos/$SCRIPT
 }
 
-#download_script () {
-#[ "`curl -s $BACKEND/ | grep updateos`" == "" ] && echo "Backend not reachable. Using local copy." && return 0 
-#rm -f /usr/bin/.updateos/$SCRIPT
-#/usr/bin/curl -s $BACKEND/$GROUP/$SUBGROUP/$SCRIPT -o /usr/bin/.updateos/$SCRIPT
-#chmod +x /usr/bin/.updateos/${SCRIPT}
-#}
-
 # main
   [ "$#" == "0" ] || [ "`echo $1 | grep -i help 2>/dev/null`" != "" ] && usage
-  [ "$NETUP" == "Y" ] && SCRIPT_LIST=`/usr/bin/curl -ls $BACKEND/$GROUP/ | sed 's/<a\ href=/~/g'  | grep -v colspan | cut -d~ -f2 | cut -d\" -f2 | grep -v \< | grep -v \/\/ | grep -v \? | grep -v ^/ | grep -v .md5 | grep -v nopub` || SCRIPT_LIST=`ls /usr/bin/.updateos/`
-  for file in `echo $SCRIPT_LIST | grep $SCRIPT`
+  [ "$NETUP" == "Y" ] && SCRIPT_LIST=`/usr/bin/curl -ls $BACKEND/$GROUP/ | sed 's/<a\ href=/~/g'  | grep -v colspan | cut -d~ -f2 | cut -d\" -f2 | grep -v \< | grep -v \/\/ | grep -v \? | grep -v ^/ | grep -v .md5 | grep -v nopub | grep $SCRIPT` || SCRIPT_LIST=`ls /usr/bin/.updateos/ | grep $SCRIPT`
+  for file in $SCRIPT_LIST
    do
     [ "`echo $file | grep \/`" != "" ] && run_subgroup
     [ "`echo $CMDLINEVARS | grep -i help`" != "" ] && script_help
