osupgrade multipath fix.

diff --git a/updateos b/updateos
--- a/updateos
+++ b/updateos
@@ -1,28 +1,37 @@
 #!/bin/bash
 
-VERSION="1.18.1"
-BACKEND="http://rhel8repo.centralus.cloudapp.azure.com/ostools-1.17"
-[ "`echo $#`" -ge "2" ] && export CMDLINEVARS="`echo $@ | cut -d" " -f2-`" || export CMDLINEVARS=""
-
+#Is root.
 ID=$(/usr/bin/id -u)
 [ $ID -ne 0 ] && echo "You must be root to run $0." && exit 1
 
-[ "`grep ' release 7.' /etc/redhat-release`" != "" ] && GROUP="rh7"
-[ "`grep ' release 8.' /etc/redhat-release`" != "" ] && GROUP="rh8"
-[ "`grep ' release 9.' /etc/redhat-release`" != "" ] && GROUP="rh9"
-
+#Init
+VERSION="1.18.1"
+LOG_FILE="/tmp/updateos.log"
+BACKEND="http://rhel8repo.centralus.cloudapp.azure.com/ostools-1.17"
+[ "`echo $#`" -ge "2" ] && export CMDLINEVARS="`echo $@ | cut -d" " -f2-`" || export CMDLINEVARS=""
 SCRIPT="$1"
 SUBGROUP="$1"
 n="${15:-20}"
 [ ! -d /usr/bin/.updateos ] &&  mkdir /usr/bin/.updateos
 
-#Internet test.
+#OS Check.
+for OSVERS in 7 8 9
+  do
+    [ "`grep " release $OSVERS." /etc/redhat-release`" != "" ] && GROUP="rh$OSVERS"
+  done
+
+#Internet check.
 ping -c 1 -W 1 8.8.8.8 >/dev/null 2>&1
-[ "$?" == "0" ] && NETUP=Y || NETUP=N 
+[ "$?" == "0" ] && NETUP=Y || NETUP=N
+
+log() {
+  echo "$@" && echo "$@" >> $LOG_FILE
+  echo >> $LOG_FILE
+}
 
 usage() {
   SUBGROUP=""
-  echo "updateos - $VERSION - USAGE: sudo updateos (groupname|scriptname)" && echo
+  log "updateos - $VERSION - USAGE: sudo updateos (groupname|scriptname)"
   echo "$GROUP"
   [ "$NETUP" == "Y" ] && SCRIPT_LIST=`/usr/bin/curl -ls $BACKEND/$GROUP/ | sed 's/<a\ href=/~/g'  | grep -v colspan | cut -d~ -f2 | cut -d\" -f2 | grep -v \< | grep -v \/\/ | grep -v \? | grep -v ^/ | grep -v \/ | grep -v .md5 | grep -v nopub` || SCRIPT_LIST=`ls /usr/bin/.updateos/`
   for SCRIPT in $SCRIPT_LIST
@@ -40,40 +49,36 @@ exit 0
 }
 
 run_subgroup() {
-[ "$NETUP" != "Y" ] && echo "Internet down. No subgroups without internet." | tee -a /tmp/updateos.log && return 0
-for SCRIPT in `/usr/bin/curl -ls $BACKEND/$GROUP/$SUBGROUP/ | grep -v $SUBGROUP | sed 's/<a\ href=/~/g'  | grep 
--v colspan | cut -d~ -f2 | cut -d\" -f2 | grep -v \< | grep -v \/\/ | grep -v \? | grep -v ^/ | grep -v \/ | grep -v .md5 | grep -v nopub`
-  do
-    echo "----> `date` - Running $GROUP $SUBGROUP $SCRIPT..." | tee -a /tmp/updateos.log
-    download_script
-    /usr/bin/.updateos/${SCRIPT} 2>&1 | tee -a /tmp/updateos.log
-    EXIT="${PIPESTATUS[0]}"
-    [ "$EXIT" != "0" ] && echo "Failed." | tee -a /tmp/updateos.log && echo "" && exit $EXIT
-    echo "----> `date` - Success." | tee -a /tmp/updateos.log
-    echo "" | tee -a /tmp/updateos.log
-  done
+  [ "$NETUP" != "Y" ] && log "Internet down. No subgroups without internet." && return 0
+    for SCRIPT in `/usr/bin/curl -ls $BACKEND/$GROUP/$SUBGROUP/ | grep -v $SUBGROUP | sed 's/<a\ href=/~/g'  | grep -v colspan | cut -d~ -f2 | cut -d\" -f2 | grep -v \< | grep -v \/\/ | grep -v \? | grep -v ^/ | grep -v \/ | grep -v .md5 | grep -v nopub`
+    do
+      log "----> `date` - Running $GROUP $SUBGROUP $SCRIPT..."
+      download_script
+      /usr/bin/.updateos/${SCRIPT} 2>&1 | tee -a $LOG_FILE
+      EXIT="${PIPESTATUS[0]}"
+      [ "$EXIT" != "0" ] && log "Failed." && exit $EXIT
+      log "----> `date` - Success."
+    done
 exit $EXIT
 }
 
 run_script() {
   SUBGROUP=""
-  echo "----> `date` -  Running $SCRIPT ..." | tee -a /tmp/updateos.log
+  log "----> `date` -  Running $SCRIPT ..."
   download_script
-  /usr/bin/.updateos/${SCRIPT} $CMDLINEVARS 2>&1 | tee -a /tmp/updateos.log
+  /usr/bin/.updateos/${SCRIPT} $CMDLINEVARS 2>&1 | tee -a $LOG_FILE
   EXIT="${PIPESTATUS[0]}"
-  [ "$EXIT" != "0" ] && echo "Failed." | tee -a /tmp/updateos.log && echo "" && exit $EXIT
-  echo "----> `date` - Success." | tee -a /tmp/updateos.log
-  echo "" | tee -a /tmp/updateos.log
-  exit $EXIT
+  [ "$EXIT" != "0" ] && log "Failed." && exit $EXIT
+  log "----> `date` - Success." && exit $EXIT
 }
 
 script_help() {
   echo "`cat /usr/bin/.updateos/$SCRIPT | grep ^#HELP /usr/bin/.updateos/$SCRIPT | sed -e 's/^#HELP\ //g'`"
-  exit 0
+exit 0
 }
 
 download_script () {
-  [ "$NETUP" != "Y" ] && echo "Internet not reachable." >> /tmp/updateos.log && return 0 
+  [ "$NETUP" != "Y" ] && log "Internet not reachable." && return 0 
   [ ! -f /usr/bin/.updateos/$SCRIPT ] && touch /usr/bin/.updateos/$SCRIPT
   [ "`curl -s $BACKEND/$GROUP/$SCRIPT.md5`" != "`md5sum /usr/bin/.updateos/$SCRIPT | cut -d" " -f1`" ] && rm -f /usr/bin/.updateos/$SCRIPT && /usr/bin/curl -s $BACKEND/$GROUP/$SUBGROUP/$SCRIPT -o /usr/bin/.updateos/$SCRIPT && chmod +x /usr/bin/.updateos/$SCRIPT
 }
@@ -82,10 +87,10 @@ download_script () {
   [ "$#" == "0" ] || [ "`echo $1 | grep -i help 2>/dev/null`" != "" ] && usage
   [ "$NETUP" == "Y" ] && SCRIPT_LIST=`/usr/bin/curl -ls $BACKEND/$GROUP/ | sed 's/<a\ href=/~/g'  | grep -v colspan | cut -d~ -f2 | cut -d\" -f2 | grep -v \< | grep -v \/\/ | grep -v \? | grep -v ^/ | grep -v \/ | grep -v .md5 | grep -v nopub` || SCRIPT_LIST=`ls /usr/bin/.updateos/`
   for file in `echo $SCRIPT_LIST | grep $SCRIPT`
-  do
+   do
     [ "`echo $file | grep \/`" != "" ] && run_subgroup
     [ "`echo $CMDLINEVARS | grep -i help`" != "" ] && script_help
     [ "`echo $file | grep -v \/`" != "" ] && run_script
-  done
-echo "updateos - $VERSION - USAGE: sudo updateos (groupname|scriptname)"
+   done
+  log "updateos - $VERSION - USAGE: sudo updateos (groupname|scriptname)"
 exit 0
