bbj install fix.

diff --git a/rh8/install_pbe b/rh8/install_pbe
--- a/rh8/install_pbe
+++ b/rh8/install_pbe
@@ -3,45 +3,36 @@
 #DESC Installs RTI Backup solution.
  
 #Solution uses Proxmox Enterprise Backups and Relax and Recover to provide for physical or virtual system-wide backups.
-#Restoration can be of a single file, multiple files, or recover and entire system from bare metal.
-#Restoration can also be onto either same hardware, or different hardware.
-#No need for a locally attached usb large drive for data.
-#Only need a usb stick for recovery/migration media.
-#Proxmox handles (out of the box) data deduplication, incremental backups methods, and encryption of backup datasets.
-#Rear handles bare metal recovery.
-#Note: no matter how good a disaster recovery solution is, it does no good without regular testing of the process.
 
 #Install Proxmox backup client.
 dnf -y copr enable derenderkeks/proxmox-backup-client
 dnf -y install proxmox-backup-client
-dnf -y copr disable derenderkeks/proxmox-backup-client
+[ "$?" != "0" ] && echo "Could not install proxmox backup client." && exit 1
 
-#Install Relax and recover install.
+#Install Relax and recover and integrate with proxmox.
 yum -y install rear
+[ "$?" != "0" ] && echo "Could not install rear." && exit 2
+[ "`grep OUTPUT=ISO /etc/rear/local.conf`" == "" ] && echo "OUTPUT=ISO" >> /etc/rear/local.conf 
+[ "`grep BACKUP=EXTERNAL /etc/rear/local.conf`" == "" ] && echo "BACKUP=EXTERNAL" >> /etc/rear/local.conf 
 
-#Integrate rear and proxmox backup client.
-#rear-external backup type
+#Vars.
+PBS_REPOSITORY=rti.myk.green:rti_servers
+SHOPCODE=12345678
+PBS_PASSWORD='2023Sadie!'
 
-#Create proxmox access keys/passphrases for backup server access as well as encrypting backups.
-#passphrases to be serial number of physical server.
+#Create namespace for customer (shopcode) in datastore.
+proxmox-backup-client namespace create $SHOPCODE --repository=$PBS_REPOSITORY
+[ "$?" != "0" ] && echo "Could not create customer name space." && exit 3
 
-#Create and schedule recovery media creation.
-#monthly
-#keep most recent only
+#Create scheduled jobs.
+[ ! -f /etc/cron.d/rti_pbe ] && cat > /etc/cron.d/rti_pbe <<EOF
+0 * * * * proxmox-backup-client backup root.pxar:/ usr2.pxar:/usr2 --repository $PBS_REPOSITORY --ns $SHOPCODE >>/usr2/bbx/log/pbe-backup-Day_$( date +%d ).log 2&>1
+EOF
+[ "$?" != "0" ] && echo "Could not create scheduled jobs file." && exit 4
 
-#Create and schedule root filesystem backups.
-#nightly
-#keep 7 days
+#Create recovery media.
+echo -n "Create recovery usb stick? "  && read ANSWER
+[ "$ANSWER" == "Y" ] && updateos create_media
 
-#Create and schedule usr2 filesystem backups.
-#hourly
-#keep 25 hours
-#keep 1 for each day up to 7 days
-
-#Create purge jobs for cleaning up old backups (retension per above).
-
-#Verify jobs.
-
-#Notifications.
- 
-exit ?
+echo "Backups configured."
+exit 0
